name: CI

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # only need the last 2 commits (including current commit) to scan diffs
      
      - name: TruffleHog OSS (Secret Scanning)
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: false 
        with:
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          path: ./
          extra_args: "--debug"
  sast-bandit:
    name: Bandit Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          targets: './src'
          severity: 'all'
          confidence: 'all'
        continue-on-error: false
