name: CI

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
   trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # only need the last 2 commits (including current commit) to scan diffs
      
      - name: TruffleHog OSS (Secret Scanning)
        uses: trufflesecurity/trufflehog@v3.90.13
        continue-on-error: false 
        with:
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          path: ./
          extra_args: --debug
      - name: Check TruffleHog Results
        if: steps.trufflehog.outcome == 'failure'
        run: |
          echo "Secrets detected by TruffleHog. Failing pipeline."
          exit 1
