name: CI

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  trufflehog-scan:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # only need the last 2 commits (including current commit) to scan diffs
      
      - name: TruffleHog OSS (Secret Scanning)
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: false 
        with:
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          path: ./
          extra_args: "--debug"

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t my-app:latest ./src

  docker-security-scan:
    name: Trivy Docker Security Scan
    runs-on: ubuntu-latest
    needs: docker-build # ensure build itself passes first
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: docker build -t vulnerable-app:latest ./src
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: vulnerable-app:latest
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  sast-bandit:
    name: Bandit Python Code Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit Security Scan
        run: bandit -r ./src --format screen

  pip-audit:
    name: Python App Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Scan dependencies
        run: pip-audit -r ./src/requirements.txt

  checkov-terraform:
    name: Checkov Terraform Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform 
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the Web Application with OWASP ZAP
    permissions:
      issues: write
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - name: Docker Build
        run: |
          docker build -t my-app ./src
          docker run -d -p 5000:5000 my-app
          sleep 10
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: 'http://localhost:5000'
          fail_action: true
